### ISSUE TITLE
Make the code look nice

### ISSUE THREAD

**Issue by cernodile** [cernodile/Intellect#1]
If you can make the code look nice, you'll earn a PR for your hacktoberfest. 👍 
Please reffer to https://github.com/standard/standard when moving things around!

**Comment by aewens** [comment]
What is your qualifications for "look nice" here? Are you wanting the code refactored, reduce long lines of code into simpler chunks, etc.

**Comment by lopno** [comment]
I'll do this in a couple of hours.

**Comment by cernodile** [comment]
@aewens Refactored, also would love if some things are moved to seperate files (like command object, calculating formulas).
